name: Static Site

on:
  push:
    branches:
      - main
      - gha-service-account
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: 'download-403601'
          service_account: 'github-actions-service-account@download-403601.iam.gserviceaccount.com'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '.'
          destination: 'justanotherwebsitebucketpleaseletmenameitthisalexwitkowski'
          parent: false

