name: Static Site

on:
  push:
    branches:
      - main
      - gha-service-account
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/525035337232/locations/global/workloadIdentityPools/justanotheridentitypool/providers/github'
          service_account: 'github-actions-service-account@download-403601.iam.gserviceaccount.com'

      - name: Upload files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: '.'
          destination: 'justanotherwebsitebucketpleaseletmenameitthisalexwitkowski'
          parent: false

